print("                       *   ")
print("                      *    ")
print("**       **         *      ") 
print("*  *   *  *        * *     ")
print("*    *    *       *****    ")
print("*         * *    *     * * ")
input("Az ablak bezárásához nyomj Entert!")
